package com.example.workshop

import kotlin.random.Random

object Storage {
    val food by lazy {
        val result = mutableListOf<FoodItem>()

        burgerNames.mapIndexedTo(result) { index, name ->
            FoodItem(
                name = name,
                description = burgerDescriptions[index],
                price = Random.nextInt(50, 1100),
                type = FoodType.BURGER
            )
        }

        pizzaNames.mapIndexedTo(result) { index, name ->
            FoodItem(
                name = name,
                description = pizzaDescriptions[index],
                price = Random.nextInt(50, 1100),
                type = FoodType.PIZZA
            )
        }

        result.shuffle()

        return@lazy result
    }

    private val burgerNames = listOf(
        "Classic Burger",
        "Cheese Burger",
        "Bacon Burger",
        "Veggie Burger",
        "BBQ Burger",
        "Mushroom Swiss Burger",
        "Spicy Jalapeño Burger",
        "Double Cheeseburger",
        "Chicken Burger",
        "Fish Burger",
        "Teriyaki Burger",
        "Buffalo Chicken Burger",
        "Pineapple Burger",
        "Avocado Burger",
        "Greek Burger",
        "Southwestern Burger",
        "Chili Burger",
        "Sliders",
        "Breakfast Burger",
        "Peanut Butter Burger",
        "Black Bean Burger",
        "Crispy Chicken Burger",
        "Philly Cheesesteak Burger",
        "Lamb Burger",
        "Pork Belly Burger",
        "Truffle Burger",
        "Caprese Burger",
        "Fried Egg Burger",
        "Sriracha Burger",
        "Hawaiian Burger",
        "Tandoori Chicken Burger",
        "Cajun Burger",
        "Ranch Burger",
        "Meat Lover's Burger",
        "Mango Salsa Burger",
        "Sweet Potato Burger",
        "Italian Sausage Burger",
        "Pulled Pork Burger",
        "Nacho Burger",
        "Fajita Burger",
        "Buffalo Cauliflower Burger",
        "Coconut Curry Burger"
    )
    private val burgerDescriptions = listOf(
        "Classic Burger: Juicy beef patty with lettuce, tomato, and onion.",
        "Cheese Burger: Topped with melted cheddar cheese and pickles.",
        "Bacon Burger: Loaded with crispy bacon and BBQ sauce.",
        "Veggie Burger: A hearty black bean patty with fresh veggies.",
        "BBQ Burger: Smothered in tangy BBQ sauce and crispy onion rings.",
        "Mushroom Swiss Burger: Topped with sautéed mushrooms and Swiss cheese.",
        "Spicy Jalapeño Burger: Packed with spicy jalapeños and pepper jack cheese.",
        "Double Cheeseburger: Two beef patties and double the cheese.",
        "Chicken Burger: Grilled chicken breast with mayo and lettuce.",
        "Fish Burger: Crispy fish fillet with tartar sauce and lettuce.",
        "Teriyaki Burger: Beef patty glazed with teriyaki sauce and grilled pineapple.",
        "Buffalo Chicken Burger: Spicy buffalo sauce with blue cheese dressing.",
        "Pineapple Burger: Grilled beef patty topped with fresh pineapple.",
        "Avocado Burger: Creamy avocado slices and salsa on a beef patty.",
        "Greek Burger: Lamb patty with feta cheese and tzatziki sauce.",
        "Southwestern Burger: Spicy beef patty with guacamole and salsa.",
        "Chili Burger: Topped with hearty chili and shredded cheese.",
        "Sliders: Mini burgers perfect for sharing, served in a variety of flavors.",
        "Breakfast Burger: Beef patty topped with a fried egg and bacon.",
        "Peanut Butter Burger: Unique flavor of peanut butter on a beef patty.",
        "Black Bean Burger: A flavorful vegetarian option made from black beans.",
        "Crispy Chicken Burger: Fried chicken breast with lettuce and mayo.",
        "Philly Cheesesteak Burger: Beef patty topped with sautéed peppers and onions.",
        "Lamb Burger: Juicy lamb patty seasoned with herbs and spices.",
        "Pork Belly Burger: Tender pork belly with caramelized onions.",
        "Truffle Burger: Luxurious truffle aioli on a beef patty.",
        "Caprese Burger: Fresh mozzarella, basil, and tomatoes on a beef patty.",
        "Fried Egg Burger: Topped with a sunny-side-up egg for extra richness.",
        "Sriracha Burger: Spicy sriracha sauce drizzled on a beef patty.",
        "Hawaiian Burger: Grilled pineapple and teriyaki sauce on a beef patty.",
        "Tandoori Chicken Burger: Spiced chicken patty with yogurt sauce.",
        "Cajun Burger: Spicy Cajun-seasoned beef patty with remoulade sauce.",
        "Ranch Burger: Creamy ranch dressing with crispy onion straws.",
        "Meat Lover's Burger: Loaded with bacon, ham, and sausage.",
        "Mango Salsa Burger: Sweet mango salsa on a spicy beef patty.",
        "Sweet Potato Burger: A flavorful sweet potato patty with spices.",
        "Italian Sausage Burger: Juicy sausage patty topped with marinara sauce.",
        "Pulled Pork Burger: Slow-cooked pulled pork with coleslaw on top.",
        "Nacho Burger: Topped with nacho cheese, jalapeños, and tortilla chips.",
        "Fajita Burger: Beef patty with sautéed peppers and onions, served with salsa.",
        "Buffalo Cauliflower Burger: Crispy cauliflower coated in buffalo sauce.",
        "Coconut Curry Burger: Flavorful coconut curry sauce on a chicken patty."
    )
    private val pizzaNames = listOf(
        "Margherita",
        "Pepperoni",
        "Hawaiian",
        "Four Cheese",
        "Meat Lover's",
        "Vegetarian",
        "Capricciosa",
        "BBQ Chicken",
        "Seafood",
        "Veggie",
        "Mushroom",
        "Funghi",
        "Pineapple",
        "Calzone",
        "Ham and Cheese",
        "Tuna",
        "Chicken Alfredo",
        "Artichoke",
        "Ricotta",
        "Spinach",
        "Bell Pepper",
        "Olive",
        "Broccoli",
        "Prosciutto",
        "Garlic",
        "Egg",
        "Beef",
        "Zucchini",
        "Eggplant",
        "Feta Cheese",
        "Salmon",
        "Apple Cinnamon",
        "Honey Walnut",
        "Truffle",
        "Brie Cheese",
        "Chili Pepper",
        "Pear and Gorgonzola",
        "Curry",
        "Smoked Salmon",
        "Pine Nut",
        "Cheddar Cheese"
    )
    private val pizzaDescriptions = listOf(
        "Classic pizza with tomato sauce, mozzarella, and fresh basil.",
        "Topped with spicy pepperoni slices and mozzarella cheese.",
        "A mix of ham, pineapple, and cheese for a sweet and savory flavor.",
        "A rich blend of mozzarella, gorgonzola, parmesan, and goat cheese.",
        " Lover's - Loaded with pepperoni, sausage, bacon, and ham.",
        "A colorful assortment of fresh vegetables and cheese.",
        "Ham, mushrooms, artichokes, and olives on a tomato base.",
        "Grilled chicken with BBQ sauce, red onions, and cilantro.",
        "A medley of shrimp, mussels, and calamari on a tomato base.",
        "Bell peppers, onions, mushrooms, and olives on a cheese base.",
        "A simple yet delicious pizza topped with fresh mushrooms.",
        "Earthy mushrooms paired with mozzarella and herbs.",
        "Sweet pineapple chunks over melted cheese.",
        "Folded pizza filled with cheese, meats, or vegetables.",
        "Classic combination of ham and gooey cheese.",
        "Tuna chunks with onions and olives for a unique flavor.",
        "Creamy Alfredo sauce topped with grilled chicken.",
        "Artichoke hearts paired with cheese and herbs.",
        "Creamy ricotta cheese spread over a thin crust.",
        "Fresh spinach leaves combined with garlic and cheese.",
        "Colorful bell peppers on a cheesy base.",
        "Black and green olives for a briny kick.",
        "Fresh broccoli florets paired with cheese.",
        "Thinly sliced prosciutto over mozzarella and arugula.",
        "Roasted garlic cloves for a rich flavor.",
        "Topped with a cracked egg for breakfast vibes.",
        "Ground beef with spices and cheese.",
        "Thinly sliced zucchini over a cheesy base.",
        "Grilled eggplant slices paired with marinara sauce.",
        "Tangy feta cheese sprinkled over the top.",
        "Smoked salmon with cream cheese and capers.",
        "Sweet apples and cinnamon for dessert pizza.",
        "Honey drizzled over walnuts for a sweet treat.",
        "Truffle oil drizzled over mushrooms and cheese.",
        "Creamy brie cheese with a hint of sweetness.",
        "Spicy chili peppers for those who love heat.",
        "Sweet pears paired with tangy gorgonzola.",
        "Curry-flavored sauce topped with chicken or veggies.",
        "Delicate smoked salmon with cream cheese.",
        "Toasted pine nuts for a crunchy texture.",
        "Sharp cheddar cheese for a bold flavor."
    )
}